apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-java-web-app
  namespace: tap-dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: java-web-app
    apps.tanzu.vmware.com/workload-type: custom-web
    apps.tanzu.vmware.com/test-type: maven
spec:
  params:
  - name: gitops_server_address
    value: https://git-codecommit.us-east-2.amazonaws.com/
  - name: gitops_repository_owner
    value: ynamadi
  - name: gitops_user_name
    value: "yunusa"
  - name: gitops_user_email
    value: "ynamadi@vmware.com"
  - name: gitops_commit_message
    value: "Test Commit"
  - name: gitops_branch
    value: master
  - name: gitops_repository_name
    value: java-web-app
  - name: gitops_ssh_secret
    value: git-ssh-devops
  - name: gitops_server_kind
    value: github
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://git-codecommit.us-east-2.amazonaws.com/v1/repos/sample-java-web-app
      ref:
        branch: develop
